//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraIngresos
    {
        public int BitacoraIngresosId { get; set; }
        public string UsuarioId { get; set; }
        public string NombreUsuario { get; set; }
        public string Accion { get; set; }
        public string Departamento { get; set; }
        public string NombreCompleto { get; set; }
        public string Terminal { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
