//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int NotificacionId { get; set; }
        public int UsuarioId { get; set; }
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public Nullable<System.DateTime> AgregadoEn { get; set; }
        public bool Leido { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
