//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosDenegadosPorRol
    {
        public int PermisoDenegadoPorRolId { get; set; }
        public int RolId { get; set; }
        public int PermisoId { get; set; }
        public System.DateTime CreadoEn { get; set; }
    
        public virtual Permisos Permisos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
